name: fluttify
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.2
  firebase_core: ^1.7.0
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - img/1000iq.gif
    - img/excuse-me.gif
    - img/holy-shet.gif
    - img/noice.gif
    - img/zootopia.gif
